"""
Biological Inventory Dashboard — SQL + Streamlit demo

An interactive dashboard for a laboratory reference-material inventory,
backed by real SQL queries (SQLite) rather than in-memory dataframe
filtering. Demonstrates: joins, aggregation, window functions, CTEs,
and views applied to a stock/inventory-management use case.

Note: all data is synthetic, generated by data/seed_data.py.
Run with: streamlit run app.py
"""

import sqlite3
from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st

DB_PATH = Path(__file__).parent / "data" / "inventory.db"

st.set_page_config(page_title="Lab Inventory Dashboard", layout="wide")


@st.cache_resource
def get_connection():
    if not DB_PATH.exists():
        # Auto-generate the synthetic database on first run (e.g. on
        # Streamlit Community Cloud, where inventory.db isn't committed).
        import subprocess
        import sys
        subprocess.run([sys.executable, str(Path(__file__).parent / "data" / "seed_data.py")], check=True)
    return sqlite3.connect(DB_PATH, check_same_thread=False)


def run_query(query: str, params: tuple = ()) -> pd.DataFrame:
    conn = get_connection()
    return pd.read_sql_query(query, conn, params=params)


st.title("🧪 Laboratory Reference Material Inventory")
st.caption(
    "Demo dashboard — SQL (SQLite) + Streamlit. All data is synthetic. "
    "Built to demonstrate intermediate SQL (joins, window functions, CTEs, views) "
    "powering an interactive inventory / stock-management tool."
)

# ------------------------------------------------------------------
# Sidebar filters
# ------------------------------------------------------------------
categories_df = run_query("SELECT DISTINCT category FROM items ORDER BY category")
categories = ["All"] + categories_df["category"].tolist()
selected_category = st.sidebar.selectbox("Category", categories)

where_clause = "" if selected_category == "All" else f"WHERE category = '{selected_category}'"

# ------------------------------------------------------------------
# KPI row — simple aggregation queries
# ------------------------------------------------------------------
kpi_query = f"""
    SELECT
        COUNT(*) AS n_items,
        SUM(stock) AS total_stock,
        SUM(CASE WHEN stock = 0 THEN 1 ELSE 0 END) AS n_out_of_stock,
        SUM(CASE WHEN DATE(reactivation_date) <= DATE('now', '+30 days') THEN 1 ELSE 0 END) AS n_due_soon
    FROM items
    {where_clause}
"""
kpis = run_query(kpi_query).iloc[0]

c1, c2, c3, c4 = st.columns(4)
c1.metric("Items in collection", int(kpis["n_items"]))
c2.metric("Total stock (units)", int(kpis["total_stock"]))
c3.metric("Out of stock", int(kpis["n_out_of_stock"]))
c4.metric("Due for reactivation (30d)", int(kpis["n_due_soon"]))

st.divider()

# ------------------------------------------------------------------
# Stock by category — GROUP BY aggregation
# ------------------------------------------------------------------
col1, col2 = st.columns([3, 2])

with col1:
    st.subheader("Stock by category")
    stock_by_cat = run_query("""
        SELECT category, SUM(stock) AS total_stock, COUNT(*) AS n_items
        FROM items
        GROUP BY category
        ORDER BY total_stock DESC
    """)
    fig = px.bar(
        stock_by_cat, x="category", y="total_stock",
        hover_data=["n_items"], color="category",
        labels={"total_stock": "Total stock", "category": "Category"},
    )
    fig.update_layout(showlegend=False, xaxis_tickangle=-30)
    st.plotly_chart(fig, use_container_width=True)

with col2:
    st.subheader("Reactivation status")
    status_query = """
        WITH status AS (
            SELECT
                CASE
                    WHEN DATE(reactivation_date) < DATE('now') THEN 'Overdue'
                    WHEN DATE(reactivation_date) <= DATE('now', '+30 days') THEN 'Due in 30 days'
                    WHEN DATE(reactivation_date) <= DATE('now', '+90 days') THEN 'Due in 90 days'
                    ELSE 'OK'
                END AS reactivation_status
            FROM items
        )
        SELECT reactivation_status, COUNT(*) AS n_items
        FROM status
        GROUP BY reactivation_status
    """
    status_df = run_query(status_query)
    fig2 = px.pie(status_df, names="reactivation_status", values="n_items", hole=0.45)
    st.plotly_chart(fig2, use_container_width=True)

st.divider()

# ------------------------------------------------------------------
# Low stock alert — queries a SQL VIEW
# ------------------------------------------------------------------
st.subheader("⚠️ Low stock alerts")
st.caption("This table queries a SQL `VIEW` (`v_low_stock`) defined in queries/example_queries.sql")

conn = get_connection()
conn.execute("""
    CREATE VIEW IF NOT EXISTS v_low_stock AS
    SELECT collection_code, taxon, category, stock,
        CASE WHEN stock = 0 THEN 'Out of stock' WHEN stock <= 2 THEN 'Low stock' ELSE 'OK' END AS stock_status
    FROM items
    WHERE stock <= 2
""")
low_stock_df = run_query("SELECT * FROM v_low_stock ORDER BY stock ASC")
st.dataframe(low_stock_df, use_container_width=True, hide_index=True)

st.divider()

# ------------------------------------------------------------------
# Movement history — INNER JOIN
# ------------------------------------------------------------------
st.subheader("📋 Recent movement history")
st.caption("Demonstrates an INNER JOIN between `movements` and `items`")

movements_query = f"""
    SELECT
        m.movement_date, m.movement_type, i.collection_code, i.taxon,
        i.category, m.quantity, m.reason, m.user
    FROM movements m
    INNER JOIN items i ON i.item_id = m.item_id
    {where_clause}
    ORDER BY m.movement_date DESC
    LIMIT 25
"""
movements_df = run_query(movements_query)
st.dataframe(movements_df, use_container_width=True, hide_index=True)

st.divider()

# ------------------------------------------------------------------
# Most-used items per category — window function (RANK)
# ------------------------------------------------------------------
st.subheader("🏆 Most frequently used items by category")
st.caption("Demonstrates a window function: RANK() OVER (PARTITION BY category ORDER BY usage DESC)")

ranked_query = """
    WITH usage_counts AS (
        SELECT i.item_id, i.category, i.collection_code, i.taxon,
               COUNT(m.movement_id) AS times_used
        FROM items i
        JOIN movements m ON m.item_id = i.item_id AND m.movement_type = 'OUT'
        GROUP BY i.item_id
    ),
    ranked AS (
        SELECT category, collection_code, taxon, times_used,
               RANK() OVER (PARTITION BY category ORDER BY times_used DESC) AS rank_in_category
        FROM usage_counts
    )
    SELECT * FROM ranked WHERE rank_in_category <= 3
    ORDER BY category, rank_in_category
"""
ranked_df = run_query(ranked_query)
st.dataframe(ranked_df, use_container_width=True, hide_index=True)

st.divider()
st.caption(
    "Full inventory table (raw `items` data) and all example SQL queries are in "
    "`queries/example_queries.sql`. See the README for how to run this locally."
)
with st.expander("View full items table"):
    full_items_query = f"SELECT * FROM items {where_clause} ORDER BY category, collection_code"
    st.dataframe(run_query(full_items_query), use_container_width=True, hide_index=True)
